-- Insert multiple job application records into the 'job_applied' table
INSERT INTO
    job_applied (
        job_id,
        application_sent_date,
        custom_resume,
        resume_file_name,
        cover_letter_sent,
        cover_letter_file_name,
        status
    )
VALUES (
        1,
        '2024-02-01',
        TRUE,
        'resume_01.pdf',
        TRUE,
        'cover_letter_01.pdf',
        'submitted'
    ),
    (
        2,
        '2024-02-02',
        FALSE,
        'resume_02.pdf',
        TRUE,
        'cover_letter_02.pdf',
        'rejected'
    ),
    (
        3,
        '2024-02-03',
        FALSE,
        'resume_02.pdf',
        FALSE,
        NULL,
        'approved'
    ),
    (
        4,
        '2024-02-03',
        TRUE,
        'resume_04.pdf',
        TRUE,
        'cover_letter_04.pdf',
        'submitted'
    ),
    (
        5,
        '2024-02-05',
        TRUE,
        'resume_05.pdf',
        TRUE,
        'cover_letter_05.pdf',
        'submitted'
    );